[package]
name = "binjs"
version = "0.4.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]
homepage = "https://binast.github.io/ecmascript-binary-ast/"
repository = "https://github.com/binast/binjs-ref"
description = "Set of tools to manipulate files in the JavaScript Binary AST format."
license = "MIT"
build = "build.rs"

[dependencies]
binjs_generic = { path = "crates/binjs_generic", version = "*" }
binjs_es6 = { path = "crates/binjs_es6", version = "*" }
binjs_io = { path = "crates/binjs_io", version = "*" }
binjs_meta = { path = "crates/binjs_meta", version = "*" }
binjs_shared = { path = "crates/binjs_shared", version = "*" }
assert_matches = "*"
bencher = "^0.1"
clap = "*"
env_logger = "^0.5"
glob = "*"
Inflector = "^0.11.2"
itertools = "*"
json = "*"
log = "*"
lzw = "*"
rand = "^0.4"
test-logger = "*"
vec_map = "*"
webidl = "*"
yaml-rust = "*"

[[bin]]
name = "binjs_encode"
path = "src/bin/encode.rs"

[[bin]]
name = "binjs_decode"
path = "src/bin/decode.rs"

[[bench]]
name = "bench_fb"
harness = false

[[bin]]
name = "compare_compression"
path = "examples/compare_compression.rs"

[workspace]
members = ["crates/*"]
